# Generated by Django 5.0 on 2023-12-11 20:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospitalapp', '0002_blogpost'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogpost',
            old_name='is_draft',
            new_name='draft',
        ),
    ]
